name: Deploy gocontrolpanel.com

on:
  workflow_call:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOYMENT_PATH: ${{ secrets.DEPLOYMENT_PATH }}
      DB_CONTAINER: ${{ secrets.DB_CONTAINER_NAME }}
      DB_NAME: gocontrolpanel
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: SSH into server, backup DB, and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            set +e  # Don't exit on errors

            # Go to deployment folder
            cd \$DEPLOYMENT_PATH || exit 0

            # Backup file path
            BACKUP_FILE=db-backup-$(date +%F).sql

            echo 'Starting database backup from container:' \$DB_CONTAINER

            # Backup if container exists and running
            if [ \$(docker ps -q -f name=^/\$DB_CONTAINER\$) ]; then
              docker exec -i \$DB_CONTAINER mysqldump -u root -p'\$MYSQL_ROOT_PASSWORD' \$DB_NAME > \$BACKUP_FILE
              echo 'Database backup saved to:' \$BACKUP_FILE
            else
              echo 'Database container not running. Skipping backup.'
            fi

            # Pull latest image and restart container
            #docker compose pull gocontrolpanel
            #docker compose up -d gocontrolpanel
          "
